
import React, { useState } from 'react';
import { generateImage } from '../services/geminiService';
import Button from './Button';
import Spinner from './Spinner';
import Alert from './Alert';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt) {
      setError('Please enter a prompt to generate an image.');
      return;
    }
    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);
    try {
      const result = await generateImage(prompt);
      setGeneratedImage(result);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'An unknown error occurred.');
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-gray-800 p-6 rounded-lg shadow-xl max-w-4xl mx-auto">
      <h2 className="text-2xl font-semibold mb-4 text-indigo-400">AI Image Generator</h2>
      <p className="text-gray-400 mb-6">Describe any image you can imagine, and let Imagen 4 bring it to life.</p>
      
      <div className="flex flex-col md:flex-row gap-4 mb-6">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g., 'A photorealistic cat astronaut floating in space, detailed, 8k'"
          className="flex-grow bg-gray-700 border border-gray-600 text-white rounded-md p-3 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition"
          rows={3}
        />
        <Button onClick={handleGenerate} disabled={isLoading || !prompt} className="md:self-start">
          {isLoading ? 'Generating...' : 'Generate Image'}
        </Button>
      </div>

      <div className="flex items-center justify-center bg-gray-900 rounded-lg p-4 min-h-[400px]">
        {isLoading && <Spinner text="Imagen is creating your vision..." />}
        {error && <Alert message={error} />}
        {generatedImage && !isLoading && (
          <div className="w-full">
            <img src={`data:image/png;base64,${generatedImage}`} alt="Generated by Imagen" className="rounded-lg shadow-lg mx-auto max-w-full h-auto object-contain" />
          </div>
        )}
        {!generatedImage && !isLoading && !error && (
            <div className="text-center text-gray-500">
                <p>Your generated image will appear here.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
